name: Code Quality Check

on:
  pull_request:
    branches: [main, master, develop]

jobs:
  lint:
    name: Run Linter
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 24
          package-manager-cache: false
          # cache: 'yarn' # Use 'yarn' or 'pnpm' if you use those package managers

      - name: Enable Corepack
        run: corepack enable

      - name: Setup Yarn
        run: corepack install --global yarn@4.10.2

      - name: Verify Yarn
        run: |
          node --version
          yarn --version

      - name: Install Dependencies
        run: yarn install --immutable

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v44
        with:
          files: |
            **/*.{js,jsx,ts,tsx}

      - name: Run ESLint
        if: steps.changed-files.outputs.any_changed == 'true'
        run: yarn eslint ${{ steps.changed-files.outputs.all_changed_files }}

      - name: Run Prettier
        run: yarn prettier

      - name: Run Typecheck
        run: yarn typecheck
